### ISSUE TITLE
是否有api开发计划

### ISSUE THREAD

**Issue by seyrenus** [chenyukang/obweb#3]
首先感谢大佬写的这个好用的系统。
然后呢我想写一个telegram机器人对接这个系统。
现在这个系统是不是还没有设计过类似的api供使用的？

**Comment by chenyukang** [comment]
> 之前看还是rust写的 今天看变成js了，貌似已经有api了。。
对，刚换成js。
感兴趣一起完善啊，我前端不太熟，边学边做的，哈哈。
